name: "🚀 Feature request"
description: "Suggest a new idea or improvement for the plugin"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!  
        Please fill out the sections below so we can understand your request better.
        
  - type: input
    id: summary
    attributes:
      label: "Feature summary"
      description: "A short, clear summary of the feature"
      placeholder: "e.g., Add support for Kotlin DSL in project wizard"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Describe your idea in detail"
      placeholder: "Why do you need this feature? How should it work?"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "How important is this feature to you?"
      options:
        - "Nice to have"
        - "Important"
        - "Critical"

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives you've considered"
      description: "If applicable, describe alternative solutions you've looked at"
      placeholder: "e.g., Using plugin X, writing my own script, etc."
